### ISSUE TITLE
composed matcher works in it block, but not from irb

### ISSUE THREAD

**Issue by tansaku** [rspec/rspec-expectations#1018]
We're working through the book rspec 3 and notice that while this code works:

```rb
require 'rspec'

describe 'composed' do
  it 'works' do
    array_hashes = [{lol: nil}] 
    expect(array_hashes[0]).to have_key(:lol)
    expect(array_hashes).to include(have_key(:lol))
  end
end
```

when in a file run from a command line, we can't get it to work from irb:

```
tansaku:~/workspace $ irb
2.3.0 :001 > require 'rspec/core'                                                                              
 => true 
2.3.0 :002 > require 'rspec/expectations'                                                                      
 => true 
2.3.0 :003 > array_hashes = [{lol: nil}]
 => [{:lol=>nil}] 
2.3.0 :005 > include RSpec::Matchers
 => Object 
2.3.0 :006 > expect(array_hashes).to include(have_key(:lol))
TypeError: wrong argument type RSpec::Matchers::BuiltIn::Has (expected Module)
        from (irb):6:in `include'
        from (irb):6
        from /usr/local/rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

any ideas?

**Comment by myronmarston** [comment]
IRB runs its repl in the context of the `main` object, which is very much an oddity.  As [this blog post explains](https://banisterfiend.wordpress.com/2010/11/23/what-is-the-ruby-top-level/), the `main` object is a weird object/class hybrid.  One of the consequences of this is that it has an `include` method defined on its singleton class, which expects a module and lets you do things like `include RSpec::Matchers`.  `RSpec::Matchers` also defines an `include` method, which returns the `include` matcher, but when you include `RSpec::Matchers` it does not take precedence over the existing `include` due to how the existing one is defined.  To work around this, you can `prepend RSpec::Matchers` onto `main`'s singleton class:

```
$ irb
irb(main):001:0> require 'rspec/expectations'
=> true
irb(main):002:0> singleton_class.prepend RSpec::Matchers
=> #<Class:#<Object:0x007ff08a8d6620>>
irb(main):003:0> array_hashes = [{lol: nil}]
=> [{:lol=>nil}]
irb(main):004:0> expect(array_hashes).to include(have_key(:lol))
=> true
```

Let me know if that makes sense.  I'm going to close this as it's simply a consequence of Ruby's `main` object, and isn't something we can or should do anything about.
