### ISSUE TITLE
`.with` with range argument does not differentiate between `..` and `...`

### ISSUE THREAD

**Issue by DawidJanczak** [rspec/rspec-expectations#1042]
The following passes:
```
expect(my_obj).to receive(:method).with(4..5)
my_obj.method(4...5)
```
`(4..5) == (4...5)` is `false` so I would imagine this assertion should fail.

**Comment by myronmarston** [comment]
I can't reproduce:

``` ruby
RSpec.describe "issue 1042" do
  it 'matches a range' do
    my_obj = double
    expect(my_obj).to receive(:method).with(4..5)
    my_obj.method(4...5)
  end
end
```

Running this spec produces:

```
Failures:

  1) issue 1042 matches a range
     Failure/Error: my_obj.method(4...5)

       #<Double (anonymous)> received :method with unexpected arguments
         expected: (4..5)
              got: (4...5)
       Diff:
       @@ -1,2 +1,2 @@
       -[4..5]
       +[4...5]
```

Can you provide an [SSCCE](http://sscce.org/) that demonstrates the issue you're seeing since I can't repro with what you've provided?

**Comment by DawidJanczak** [comment]
Apologies @myronmarston, it's not `expect` that fails, but `allow`:
```
RSpec.describe "issue 1042" do
  it 'matches a range' do
    my_obj = double
    allow(my_obj).to receive(:method).with(4..5).and_return(123)
    expect(my_obj.method(4...5)).to eq(123)
  end
end
```
passes. It actually passes with any range for that matter, but fails if argument type is different (e.g. `with('foo')`.

Since it's `allow`, not `expect` I'll re-open this in `rspec-mocks`, but could you please verify you can reproduce this and that it is not expected behaviour? Thank you.

**Comment by myronmarston** [comment]
I can't reproduce.  Here's the output I get from the spec you posted:

```
  1) issue 1042 matches a range
     Failure/Error: expect(my_obj.method(4...5)).to eq(123)

       #<Double (anonymous)> received :method with unexpected arguments
         expected: (4..5)
              got: (4...5)
       Diff:
       @@ -1,2 +1,2 @@
       -[4..5]
       +[4...5]

        Please stub a default value first if message might be received with other args as well.
```

It's failing as I would expect.  There's probably something in your environment causing the different behavior (e.g. a monkey patch to `Range`).  If you want me to continue looking into this, please provide a git repo I can clone that demonstrates the issue.

**Comment by DawidJanczak** [comment]
OK so RSpec on its own works fine, it looks like it's either Rails or `rspec-rails` issue. SSCCE will unfortunately won't be Short as it includes whole Rails env, but I ran `rails new` with `rspec-rails` here: https://github.com/DawidJanczak/rspec-allow-bug This spec https://github.com/DawidJanczak/rspec-allow-bug/blob/master/spec/range_spec.rb passes for me where we `require 'rails_helper'`, but fails as it should when we just `require 'spec_helper'`. To be more precise this line loading Rails env https://github.com/DawidJanczak/rspec-allow-bug/blob/master/spec/rails_helper.rb#L4 seems to introduce incorrect behaviour.
I don't think it's monkey patching `Range` because an assertion `expect(4..5).to eq(4...5)` fails as it should regardless of requiring `rails_helper`.

**Comment by myronmarston** [comment]
Thanks for the git repo demonstrating the issue.  It's fine it wasn't short; the important thing is that it reproduced the issue, and your part (the spec) was really short :).

Internally, RSpec uses `===` when matching arguments.  This provides lots of flexibility; it allows you to do things like pass a regex to `with` to match on string arg, or pass any RSpec matcher (all of which implement `===` as an alias for `matches?`).

Normally, `(4..5) === (4...5)` returns `false`, but when Rails is loaded, it returns `true`.  This is happening because Rails [monkey patches `Range#include?`](https://github.com/rails/rails/blob/v5.2.0.beta2/activesupport/lib/active_support/core_ext/range/include_range.rb) and [`Range#===` delegates to `include?`](https://github.com/ruby/ruby/blob/v2_5_0/range.c#L1106-L1129).

I'm not convinced the ActiveRecord monkey patch is a good idea, but arguing that with the Rails team is probably a losing battle (particularly since people's apps now depend on that behavior).

You can work around this in your spec, though.  To make an argument matcher _more_ strict, so that it matches only if the passed arg is `==` instead of `===`, you can wrap the expected arg with a matcher like `an_object_eq_to`:

``` ruby
RSpec.describe "issue 1042" do
  it 'matches a range' do
    my_obj = double
    allow(my_obj).to receive(:method).with(an_object_eq_to 4..5).and_return(123)
    expect(my_obj.method(4...5)).to eq(123)
  end
end
```

The object returned by `an_object_eq_to` implements `===` so that it matches only if the objects being compared are _exactly_ equal, providing the behavior you want.

**Comment by DawidJanczak** [comment]
That all makes complete sense (apart from Rails monkey patching, that is). Thanks for the explanation @myronmarston!
