### ISSUE TITLE
to_stdout not working with Logger?

### ISSUE THREAD

**Issue by jcavalieri** [rspec/rspec-expectations#1063]
### Subject of the issue
I'm trying to test a custom logger, that utilizes Ruby's core logger. It appears that I can not use to_stdout or to_stderr with it. Is there some special handling going on with Logger? Or do I have something wrong with my syntax?

### Your environment
* ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin17.0]
* rspec-expectations (~> 3.7.0)

### Steps to reproduce
```
     Failure/Error:
       expect do
         logger = Logger.new(STDOUT)
         logger.warn('foo')
       end.to output.to_stdout

       expected block to output to stdout, but did not
```

### Expected behavior
To be true

### Actual behavior
>expected block to output to stdout, but did not

**Comment by myronmarston** [comment]
This is a known [documented](http://rspec.info/documentation/3.7/rspec-expectations/RSpec/Matchers.html#output-instance_method) issue:

> Note: to_stdout and to_stderr work by temporarily replacing $stdout or $stderr, so they're not able to intercept stream output that explicitly uses STDOUT/STDERR or that uses a reference to $stdout/$stderr that was stored before the matcher was used.

Your code needs to use `$stdout` instead of `STDOUT` if you want to use `output(...).to_stdout`.  Otherwise, you should be able to use `output(...).to_stdout_from_any_process`, which should work with `STDOUT`, but is ~30x slower in our benchmarks.

**Comment by jcavalieri** [comment]
Thanks @myronmarston.
