### ISSUE TITLE
expect(HashWithIndifferentAccess).to include(Symbol) behaves differently in 3.8.0

### ISSUE THREAD

**Issue by Kjarrigan** [rspec/rspec-expectations#1068]
### Subject of the issue
Today I upgraded to the latest 3.8.0 rspec release and found that a specific test breaks now. After tinkering with it a bit I could isolated the problem. See the code snippet below.

### Your environment
* Ruby version: tested with 2.3, 2.5, 2.6rc2
* rspec-expectations version: 3.7.0 and 3.8.0

### Steps to reproduce
```ruby
require 'active_support/core_ext/hash/indifferent_access'

RSpec.describe 'include matcher difference between 3.7.0 and 3.8.0' do
  it 'should include the keywords' do
    hsh = HashWithIndifferentAccess.new
    hsh['foo'] = 'bar'

    expect(hsh).to include(:foo)
  end
end
```

### Expected behavior

Testsuite passes as in 3.7.0

### Actual behavior

Testsuite fails in 3.8.0

EDIT: Fixed the versions...

**Comment by eitoball** [comment]
I think that this is becasue `include` matcher calls `#to_hash` (#1012) .

**Comment by myronmarston** [comment]
Thanks for reporting this @Kjarrigan and for finding the root cause @eitoball.

I think the solution is to modify the code added in #1012 to only call `to_hash` if the object is not already a hash.  Since `HashWithIndifferentAccess` is already a hash we'll avoid it in that case, and more generally, if we already have a hash no conversion is needed (and we want to work with the hash the user passed us).

Does someone want to work up a fix?  I'm unlikely to get to this today, but could review and merge a PR.  Note that when you add a spec for this, please do not add a dependency on activesupport; instead add a class to rspec-expectations' spec suite that mimics this aspect of `HashWithIndifferentAccess` (you could even call it the same thing) but doesn't pull in all of the code of activesupport's class.

**Comment by eitoball** [comment]
> Does someone want to work up a fix? 

I do.

**Comment by eitoball** [comment]
I just submitted #1069.

**Comment by myronmarston** [comment]
A fix for this has been merged.  I was going to release it, but I don't have the private key we use to sign our released gems available on my work computer, so a release will have to wait until I'm home tonight unless @JonRowe or @samphippen get to it before then.

**Comment by Kjarrigan** [comment]
Good job guys and thanks for the fast fix. :+1:

**Comment by myronmarston** [comment]
3.8.1 is out with a fix.

**Comment by lamont-granquist** [comment]
:+1:
