### ISSUE TITLE
Strict predicate matchers

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec-expectations#1102]
### Subject of the issue

It would be great to have a configuration for predicate matchers to be "strict" in the sense that they require the return result to be a boolean and not something that is truthy or falsey. It's easy for these methods to have values that creep their way to the client side in tricky to debug ways, so we try as much as possible in our codebase to enforce that they always return `true` or `false`. Right now we avoid the predicate matchers and instead use `expect(thing.there?).to be true`.

### Your environment
* Ruby version: 2.5
* rspec-core version: 3.8

### Steps to reproduce

```rb
class MyClass
  def there?
    'yep'
  end
end

it 'returns true' do
  expect(MyClass.new).to be_there
end
```

### Expected behavior
The above test fails because the method returns `'yep'` instead of `true`.

### Actual behavior
The above test passes.

**Comment by mockdeep** [comment]
Yeah, we'll probably continue using the more precise syntax for now. Might end up looking into custom matchers at some point.

**Comment by marcandre** [comment]
@JonRowe Could you revisit this please?

>  its well documented that `rspec-expectations` predicate matchers obey Ruby's truthiness rules

I don't believe this is accurate. For example, the doc gives the following example:

> Ruby objects commonly provide predicate methods:
```ruby
    7.zero? # => false
    0.zero? # => true
    [1].empty? # => false
    [].empty? # => true
    { :a => 5 }.has_key?(:b) # => false
    { :b => 5 }.has_key?(:b) # => true
```ruby

> You could use a basic equality matcher to set expectations on these:

> 7.zero?.should == true # fails with "expected true, got false (using ==)"

> ...but RSpec provides dynamic predicate matchers that are more readable and
provide better failure output.

Lacking from the doc: "but with a less strict matcher corresponding to `be_truthy` / `be_falsey` (and I've stated clearly what I think of those). All examples given return`true` / `false`. 

Moreover, the failure messages are also wrong:

```
expected `obj.foo?` to return false, got 42
# or
expected `obj.foo?` to return true, got nil
```

> and I'm not sure I want to change that.

I feel that these matchers are imprecise and error prone. A method returning `"true"` and `true` are not quite the same; one could be an unwanted effect in the code.

Assuming you still like the imprecise matchers, I would propose:
1) Specify clearly in the doc the default behavior
2) Rephrasing the error messages to say "be falsey/truthy" instead of "return false/truthy"
3) Adding a config `strict_predicate_matchers` that would actually do `== true/false` and the error messages would be the current ones.

I will glady provide a PR for this.

> We have the option to be more precise as you've mentioned

It's a really bad option, as it makes the spec less readable and the error messages much less informative

**Comment by pirj** [comment]
Given the inconsistencies of our current doc with the behaviour, I'm in favour of this proposal.

Let's postpone the `truthy`/`falsey` discussion and change of the default setting for `strict_predicate_matchers` until the release of 3.99.

**Comment by marcandre** [comment]
> change of the default setting for `strict_predicate_matchers` until the release of 3.99

The setting doesn't exist yet; I'm proposing that one is created. I believe the default should be `true` but as long as the setting exists I'll be happy. Will a PR be accepted?

**Comment by pirj** [comment]
I clearly understand that. Once this setting is added, it would be easier to discuss to flip its default, but only during a major version update.

**Comment by marcandre** [comment]
Oh, sorry, I misread then. So I'll work on a PR then, or did you want to handle it @pirj

**Comment by pirj** [comment]
It's up to @JonRowe to decide.

**Comment by JonRowe** [comment]
For context, I originally assessed this as a bug report and I lacked (and still lack) the time to implement anything to improve the situation, as it stands it works as designed.

However @marcandre @pirj if either of you wants to work on an opt-in config for this matcher to make it stricter I'd be happy to review it. I'm generally a fan of stricter matchers too but I definitely don't want to change the default in 3.x (breaking change). I'd be happy to add a warning in 3.99 and then change the default in 4.x but I'd also want to announce those plans early on to get consensus.

**Comment by pirj** [comment]
Awesome, thanks!

**Comment by JonRowe** [comment]
New PR for feature request, as mentioned this is a bug report.

**Comment by pirj** [comment]
Sounds good. 👍 

I've slightly changed the wording of the description so it looked more like a feature request than a bug report.

**Comment by marcandre** [comment]
🎉 Awesome 😃 

@pirj let me know if you want to handle this, otherwise I'll check it out in the next few days

**Comment by pirj** [comment]
@marcandre Highly appreciate if you can take care of this, I have a reduced capacity those days unfortunately.
