### ISSUE TITLE
Testing long code-block loop continues after expectation is met (Test is passing)

### ISSUE THREAD

**Issue by luke-hill** [rspec/rspec-expectations#1140]
### Subject of the issue
When testing a length loop, but you only want to test a small number of iterations, the rspec expectations don't early terminate (I would expect them to)

### Your environment
* Ruby version: 2.5
* rspec-expectations version: 3.8

### Steps to reproduce
```
it 'should not continue forever' do
    expect(Class).to receive(:new).at_least(:once)

    loop do
      Class.new
      @a ||= 0
      puts @a
      @a += 1
    end
  end
```

### Expected behavior
This test should run in fractions of a second and pass. Because clearly an instance of `Class` is created. The other items are just there to aid debugging.

### Actual behavior
The loop continues forever.

If you modify the code block to the following

```
it 'should not continue forever' do
    expect(Class).to receive(:new).at_least(:once)

    loop do
      Class.new
      @a ||= 0
      puts @a
      @a += 1
      break if @a >= 10
    end
  end
```

The test passes.

Use-case: I'm testing a CLI where the condition is re-evaluated each time and then ran. I wasn't sure how best to test it.

My code is roughly like this.

```
def method
  MUD::Actions::Command.new(user_input) while player.alive?
end
```

And my associated test
```
    it 'delegates input commands to the Command Action class' do
      expect(MUD::Actions::Command).to receive(:new).with(user_input).at_least(:once)

      play_game
    end
```

**Comment by JonRowe** [comment]
:wave: As you've used `at_least(:once)` the expectation is passing, so there is nothing to stop the loop. You are responsible for terminating your own loop.

**Comment by luke-hill** [comment]
I've just checked and yes, you are right that if I set the condition to at_most(:once), it fails once created twice.

However this raises an important issue - That of optimisation. I'm confused why it wouldn't just pass the test. This makes it very hard to test this system where all I care about is checking that a class is created (I've got extensive unit tests there), essentially I'm just doing a simple delegation test but it feels like it's impossible to do with rspec?

If it's not a bug, could you maybe suggest how I avoid having to wrap my code in some sort of ugly `Timeout.timeout` block

**Comment by JonRowe** [comment]
It doesn't pass because your test block hasn't exited, there is no way for RSpec to know wether this is expected or not. You should not be running infinite loops in tests. Standard Ruby *will* block in this fashion.

Personally, I would refactor my code here... Something alone these lines

```
module Game
  module_function

  def run(forever: true)
    setup
    running = true
    while running do
      process_turn
      running = forever
    end
  end

  def setup
  end

  def process_turn
  end
end
```

This means you can unit test your setup step, your turn step, or your entire loop by passing in the option to only run once..

**Comment by pirj** [comment]
Since `loop` is a regular Ruby construct, and if you expand it, e.g.:
```ruby
      Class.new
      @a ||= 0
      puts @a
      @a += 1
# iteration 2
      Class.new
      @a ||= 0
      puts @a
      @a += 1
```
it would be strange for RSpec to stop evaluating the scenario further after all expectations were met.

Another couter-argument is that there's nothing that prevents you from having
```ruby
  fail 'haha' if @a > 3
```
somewhere in the loop, and this would normally fail the spec (without an `expect { ... }.to raise_error`).
