### ISSUE TITLE
raise_error obscures failures from nested expectations

### ISSUE THREAD

**Issue by dmolesUC** [rspec/rspec-expectations#1293]
### Subject of the issue

Given a method with a block expectation, called by another method with a `raise_error` expectation, if the block expectation fails, the failure isn't reported directly, but rather as a failure of the `raise_error` expectation to get the expected error.

### Your environment

* Ruby version: 2.7.2
* rspec-expectations version: 3.10.1

### Steps to reproduce

Run the following test:

```ruby
class Foo
  def frob(_arg)
    nil
  end
end

class Bar
  def initialize(foo)
    @foo = foo
  end

  def frobnitz(arg)
    raise ArgumentError unless @foo.frob(arg)
  end
end

describe Bar do
  let(:foo) { Foo.new }
  let(:bar) { Bar.new(foo) }

  describe :frobnitz do
    it 'frobs foo' do
      expect(foo).to receive(:frob) do |arg|
        expect(arg).to include('baz')
      end

      expect { bar.frobnitz('qux') }.to raise_error(ArgumentError)
    end
  end
end
```

### Expected behavior

- test should fail with

  ```txt
  expected "qux" to include "baz"
  ```

### Actual behavior

- test fails with

  ```txt
  expected ArgumentError, got #<RSpec::Expectations::ExpectationNotMetError: expected "qux" to include "baz"> with backtrace:
    # ...
  ```

### Workaround

Replace `expect {...}.to raise_error(...)` with a `begin/rescue/rescue` block, as:

```ruby
begin
  bar.frobnitz('qux')
rescue RSpec::Expectations::ExpectationNotMetError
  raise
rescue => e
  ex = e
end

expect(ex).to be_a(ArgumentError)
```

Note: This workaround isn't very good as it doesn't handle other RSpec errrors like `RSpec::Mocks::MockExpectationError`. (It would be nice if RSpec errors had a common superclass.) There's probably a better one, but it's past my bedtime.

**Comment by JonRowe** [comment]
I'm on the fence about this, you are expecting an `ArgumentError` and one isn't happening, thus the failure is valid, its a bit of a chicken and the egg question to decide which failure should take precedence, (we also use this matcher to test ourselves and extensions to RSpec, so its not a behaviour that could be changed overnight).

We could at least consider a common exception parent over in rspec support, which could even not be a breaking change as it would just be an additional ancestors, thoughts @pirj?

**Comment by dmolesUC** [comment]
I suppose another (probably better) workaround would be to capture the argument in a local variable and assert on it separately, after `expect {}.to raise_error`, so that expectation doesn't interfere with throwing the `ArgumentError` in the first place.

**Comment by pirj** [comment]
Your `raise ArgumentError` is never reached because `@foo.frob(arg)` is causing the example to fail.

I'm getting lost in what you are testing here exactly.
There are two things that `frobnitz` does:
1. Forwards to its `arg` to `@foo.frob(`
2. `raise`s `ArgumentError` if the returned result of this forwarding is falsey

As you're stubbing `frob` and don't configure its response (`.and_return`/`.and_call_original`/...), it will always return `nil`, and `ArgumentError` will always be triggered. But then it's deceiving to expect `ArgumentError` to be raised because it is due to the stubbing, not to the behaviour of those classes.

I suggest splitting this example into two more focused ones:

```ruby
class Foo
  def frob(arg)
    arg == 'qux' ? 1 : false
  end
end

class Bar
  def initialize(foo)
    @foo = foo
  end

  def frobnitz(arg)
    raise ArgumentError unless @foo.frob(arg)
  end
end

RSpec.describe Bar do
  let(:foo) { Foo.new }
  let(:bar) { Bar.new(foo) }

  describe '#frobnitz' do
    it 'forwards' do
      arg = double
      expect(foo).to receive(:frob).with(arg).and_return(true)
      bar.frobnitz(arg)
    end

    it 'raises ArgumentError when Foo.frob returns a falsey value' do
      expect { bar.frobnitz('') }.to raise_error(ArgumentError)
      expect { bar.frobnitz('qux') }.not_to raise_error
    end
  end
end
```

On a side note, please notice that I went with:
```ruby
expect(foo).to receive(:frob).with('baz')
```
instead of `receive(:frob) do`. Not sure what was the intent of using `include`, to match that `bar` is part of the passed String argument?

I don't think that inheriting `ExpectationNotMetError` from some common class would make any difference.

From my point of view, there is nothing actionable here, nothing that we could fix.
