### ISSUE TITLE
How to chain `output` matcher with check for return result?

### ISSUE THREAD

**Issue by abitrolly** [rspec/rspec-expectations#1441]
### Subject of the issue

Chaining  `output` and `be` matcher gives this block pass error.

> You must pass an argument rather than a block to `expect` to use the provided matcher (output "success\n" to stdout and equal false), or the matcher must implement `supports_block_expectations?`.

### Your environment

* Ruby version: 3.2.2
* rspec-expectations version:  3.12.2

### Steps to reproduce

Have  a function that returns false and and prints "success" to stdout. The try to chain the expectations to test both output and return value in one go.

```ruby
def false_success
  puts "success"
  return false
end

RSpec.describe "false success function" do
  it "works" do
    expect { false_success }
      .to output("success\n").to_stdout
      .and be(false)
  end
end
```

### Expected behavior

All checks pass.

### Actual behavior

```ruby
F

Failures:

  1) false success function works
     Failure/Error:
       expect { false_success }
         .to output("success\n").to_stdout
         .and be(false)
     
       You must pass an argument rather than a block to `expect` to use the provided matcher (output "success\n" to stdout and equal false), or the matcher must implement `supports_block_expectations?`.
     # ./let_spec.rb:8:in `block (2 levels) in <top (required)>'

Finished in 0.05108 seconds (files took 0.31973 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./let_spec.rb:7 # false success function works
```

**Comment by pirj** [comment]
```
expect {
  expect(false_success).to be(false)
}
      .to output("success\n").to_stdout
```

**Comment by pirj** [comment]
A pr that would document expectation nesting works is welcome. Merry Xmas!

**Comment by abitrolly** [comment]
Thanks. ) I guess this issue already serves as a documentation.

The syntax is not readable. This morning I wouldn't understand it. :D
My original intention was to use a helper like this one hinted by Gemini Pro.

```ruby
    output = capture_stdout do
      result = false_success
    end

    expect(result).to eq(false)
    expect(output).to eq("success\n")
```

The problem is - such helper doesn't exist.

**Comment by pirj** [comment]
> this issue already serves as a documentation

It does not. We reserve our issue tracker for bugs and feature requests.
We use runnable cucumber specs to generate public documentation.

If something that is a core functionality, and composing block matchers with value matchers by nesting expectations is - it is worth documenting.
Another case for nested expectations is to test custom matchers.

As confusing nesting expectations can look at first, they provide a generic mechanism. A matcher you suggest would only work to capture output, and it won’t work for the `yield` matcher, rspec-rails’ `change` etc. Because of this, and because it duplicates what we have already, we won’t be interested in including it in the codebase.
