### ISSUE TITLE
Suggestion: raise_error matcher should have no default exception type or default to StandardError

### ISSUE THREAD

**Issue by jstultz** [rspec/rspec-expectations#655]
Using the `raise_error` matcher without specifying a particular error type is quite dangerous, as it  swallows any sort of exception, including syntax errors and rspec expectation errors. It's hard for me to imagine a reasonable justification for the author of a test not caring at all what type of error is thrown; in my opinion it would be more helpful to users of rspec to be forced to think at least a little bit about what type of error they are expecting.

If there's no agreement on that, then at least perhaps it might be worth considering changing the default from `Exception` to `StandardError`.

For quick reference:
https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/raise_error.rb#L11
https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/raise_error.rb#L42-L49

**Comment by samphippen** [comment]
I think the behaviour should stay as it is now. As Myron has pointed out `expect { raise Exception }.to raise_error` should pass. Also, the terseness of just writing `raise_error` is fine in some situations, especially if you're not sure what the error class you're going to get.

**Comment by jstultz** [comment]
I disagree that the terseness of `raise_error` with no arguments is fine in that situation (and I have yet to see an example situation where it is). If you are writing a test that asserts that some piece of code raises an exception, you should know what class of exception it is supposed to raise. If you don't, you ought to find out (this is not difficult). Not specifying a specific exception class is not only less helpful to others (many people read tests to help understand how some code works and how to use it), but it is also bug prone. Literally *anything* can go wrong inside the `expect` block if you are simply asserting that something throws *some* exception. You may think you are asserting that some method under test throws an exception when used in a certain way, or under certain conditions, but in fact you just wrote the test incorrectly. Perhaps a typo:

```ruby
  it 'throws an exception when given no arguments' do
    expect {
      "test".splitt
    }.to raise_error
  end
```

**Comment by avdi** [comment]
Having thought about this a little bit I think I could get behind, at the very least, having a bare `raise_error` cause a warning. A warning which could be disabled in config.

I have to say I have a hard time coming up with an example of time when a bare `raise_error` was a good idea. They do tend to hide mistakes.

**Comment by myronmarston** [comment]
> Having thought about this a little bit I think I could get behind, at the very least, having a bare `raise_error` cause a warning. A warning which could be disabled in config.

This seems like a good solution, IMO.  If a user wants to use bare `raise_error` in the face of a notification that it's prone to false positives, more power to them.  It's not our job to enforce how they use it, but we should let them know that it's a problematic practice.

**Comment by amilligan** [comment]
I appreciate that I'm late to this party, as usual, but this warning just started cropping up in my current project, and I'm unconvinced by this change.

My primary concern when writing my specs is that they reflect what I mean to say.  Frankly, when I write

`expect { ... }.to raise_error`

that pretty clearly states what I want it to say.  I want that code to raise an error.  Which error?  I don't care!  If I had cared, I would have included it in the expectation.

Ruby, in general, is not a particularly exception-oriented language; I don't really expect a lot of the exceptions I throw to be caught.  If an exception occurs it's generally because of something stupid I did, I look at the stack trace, and I go fix it.  It doesn't matter what the exception class is, and I often take advantage, in specs, of the fact that I don't care what the exception is when something stupid happens, and just let the language blow up in whatever way it likes.

Obviously this isn't universally true; sometimes you care that an action throws an ActiveRecord::RecordNotFound, but then you say what you mean ('I want *this* exception') and everyone is happy.

So, I don't expect you will roll back this change, but I do have one related request.  Please, don't start lumping all possible false positives under the new config option.  I would like to turn this warning off without potentially missing much more interesting and/or useful potential false positive warnings.

**Comment by myronmarston** [comment]
> Please, don't start lumping all possible false positives under the new config option. I would like to turn this warning off without potentially missing much more interesting and/or useful potential false positive warnings.

We reallllyyy don't want to go down the path of a separate warning for each potential false positive, so I think it's unlikely we'd do this.  Every new config increases our maintenance burden.

That said, if it was clear from community feedback that many in the community want separate configs, it's something I'd consider.

**Comment by jstultz** [comment]
If you really don't want to care what kind of error is raised, you can still do that without a warning: just expect to raise `Exception`.

**Comment by amilligan** [comment]
@myronmarston I understand your reticence.  I wouldn't want to support something that turns into JSHint, either.  However, you regularly state that you want Rspec to be a flexible tool that people can use as they see fit.  You've now fundamentally eliminated a usage pattern (warnings are equivalent to errors in a build, as far as I'm concerned) that I consider useful and expressive.  I can restore that behavior only by turning off all warnings, current and future, that may or may not be interesting to me.  That's a shitty tradeoff, in my opinion.

I'm just a guy, and I'm just offering my opinion.  But, few things frustrate me more than tools that make inflexible choices to restrict expressiveness.  That path leads to Java.

(Not that I really mean to compare Rspec to Java; that's a bit like comparing the driver who cut you off in traffic to Hitler.  I write a metric shit ton of Rspec, and I think it's a great tool.)

**Comment by jstultz** [comment]
As I've said, the usage pattern has not been fundamentally eliminated. `expect { ... }.to raise_error(Exception)`

**Comment by myronmarston** [comment]
Here's your config option:

``` ruby
module AllowBareRaiseErrorWithoutWarnings
  def raise_error(*args)
    args = [Exception] if args.empty?
    super(*args)
  end
end

RSpec.configure do |c|
  c.include AllowBareRaiseErrorWithoutWarnings
end
```

Put that in `spec_helper.rb` and in your project, base `raise_error` will not issue warnings.

**Comment by amilligan** [comment]
@myronmarston Thanks for the work-around.  I'll use that in my current project.

However, I'm not terribly concerned about working around the warning in one project; I can remove it without too much trouble.  I brought up the issue more due to the precedent.  Workarounds are fine until you inevitably start a new project, or inherit an old one, and have to go search for all the hacks again.

Regardless, no need to continue the debate.  As I stated, I don't expect you to roll anything back, I just wanted to express my reservations.

**Comment by amilligan** [comment]
@jstultz Clear your mind.  Reread.  Understand.
