### ISSUE TITLE
Negate Compound Matchers

### ISSUE THREAD

**Issue by elado** [rspec/rspec-expectations#664]
With compound matchers it's possible to do:

``` ruby
expect { something }
  .to change(Something, :count).by(1)
  .and change(SomethingElse, :count).by(1)
```

Is it possible to negate an `and`? E.g.

``` ruby
expect { something }
  .to change(Something, :count).by(1)
  .and_not change(SomethingElse, :count).by(1)
```

(Without using nested `expect`s and `to_not`s).

**Comment by doits** [comment]
`RSpec::Matchers.define_negated_matcher :not_change, :change` should be included into RSpec by default IMO!

**Comment by myronmarston** [comment]
> RSpec::Matchers.define_negated_matcher :not_change, :change should be included into RSpec by default IMO!

As a general rule, we don't include negated matcher aliases in RSpec. It's one line of code for users to add one to a project.  I don't see what's special about the `change` matcher that warrants us including a negated alias for it but not other matchers...and we definitely don't want to include negated aliases for all matchers since it would greatly increase the API surface area.

Plus, different users have different preferences on phrasing for the negated form; I'm favor `avoid_changing` over `not_change`, for example.

**Comment by myronmarston** [comment]
@doits one potential solution for what you're asking for is a gem of negated matchers.  It could provide negated aliases of all built-in RSpec matchers.  Would you have any interest in providing the community with such a gem?

**Comment by doits** [comment]
@myronmarston the only negated matcher I've missed multiple times over the last years was this `.not_change` in combination with `.and` (I always rewrote my specs then but did not investigate further to find this easy solution).

When I think more about it, the`and_not`-expression is really what is missing for me (like in OP requested), but I understand the reasons why you don't want to include it (also after reading #493).

When I start to define more negated matchers (now knowing `RSpec::Matchers.define_negated_matcher`) I might create a gem, but creating a gem for one line now (in my case) is overkill.
