### ISSUE TITLE
Why can't you use .or()'ed matchers with .to_not ?

### ISSUE THREAD

**Issue by postmodern** [rspec/rspec-expectations#720]
They seems like an unnecessary restriction. It should be possible to apply [De Morgan's Law](http://en.wikipedia.org/wiki/De_Morgan%27s_laws) and apply the negation to the compound matcher.

**Comment by myronmarston** [comment]
We chose not to support negation for a compound matcher expression because there's a bit of ambiguity.

Consider this expression:

``` ruby
expect(person).not_to be_over_30.and have_type_o_blood
```

Which of these does this mean?

* `not(be_over_30 and have_type_o_blood)`
* `not(be_over_30) and not(have_type_o_blood)`

The former is the more natural/correct way to implement it (since the expression `be_over_30.and have_type_o_blood` is being passed to `not_to`), but is probably not what the user intends.  Consider that `not(be_over_30)` is a stronger expectation than `not(be_over_30 and have_type_o_blood)` -- `not(be_over_30)` will only pass if and only if the person is 30 or under.  But once you have `not(be_over_30 and have_type_o_blood)` you are allowing the person to be over 30, because this expression will pass if the person does not have type O blood, irregardless of what age the person is.

You can think of a particularly pathological case: `expect(x).not_to m1.and m2.and m3...and m99.and m100`.  In this expression you have 100 matchers, but due to the negation, only one of them needs to negatively match; the other 99 could match or not and the entire expression will pass.  You're not really saying anything.

This is one of the reasons we added `define_negated_matcher` in RSpec 3.1 -- it allows you to define negated versions of individual matchers and then use in them in a positive compound expression to be explicit about which things you actually want to negate.

Example:

```
RSpec::Matchers.define_negated_matcher :be_under_31, :be_over_30
RSpec::Matchers.define_negated_matcher :have_a_blood_type_besides_o, :have_type_o_blood
expect(person).to be_under_31.and have_a_blood_type_besides_o
```

Or, if the user really wants the behavior of the 1st bullet point (even though it's not generally recommended), they can achieve this with `define_negated_matcher` and `or`:

``` ruby
expect(person).to be_under_31.or have_a_blood_type_besides_o
```

This forces the user to be explicit about what they mean which I think is a good thing.

Now, I've been talking about negating `and`, but you're asking about `or`.  I honestly haven't thought about `or` as much (`and` is the more common of the compounds, in my experience).  You're right that `or` makes more sense -- the natural/correct way to implement it strengthens the expectation with each additional matcher in the `or` expression.  So it's not as problematic as negating `and`.  It might be worth supporting, but it might also be confusing to support negation for one compound operator but not the other.

Thoughts?

**Comment by postmodern** [comment]
I can see that potential confusion. To me the `.not_to` and match expression are two separate components, and that the `.to` or `.not_to` are applied to the entire expression. I would simply apply De Morgan's Law to the entire expression.

**Comment by myronmarston** [comment]
> To me the .not_to and match expression are two separate components, and that the .to or .not_to are applied to the entire expression. I would simply apply De Morgan's Law to the entire expression.

I agree -- this is how I would interpret it, too.  The problem is that applying that to `and` compounds creates a weakened expectation that gets weaker with every additional compounded matcher.  I worry that some users would not realize this and it would be a major gotcha.  As maintainer, I always want to be careful about introducing features that are prone to producing false positives without the user realizing it -- and I worry that `.not_to matcher.and matcher` would do that.

But as I said, I'm open to supporting this for `or` even if we don't support it for `and`.  Do you think it would be confusing to support it for one but not the other?

**Comment by JonRowe** [comment]
I think we should leave this as is TBH

**Comment by myronmarston** [comment]
Closing due to lack of response from @postmodern.
