### ISSUE TITLE
Add a .not() operator for negating matchers

### ISSUE THREAD

**Issue by postmodern** [rspec/rspec-expectations#721]
I commonly find myself wanting to write compound matches, but I need to negate one of the matches.

    .to include(a: '1').and.not(include(b: '2'))

**Comment by myronmarston** [comment]
We attempted this previously (see #505) but ran into problems.  Providing an understandable `description` and `failure_message` from a negated matcher becomes a natural language problem that's out of scope for what RSpec is meant to do.  Instead, we decided to add `RSpec::Matchers.define_negated_matcher` -- that allows you to define a new matcher that is the negation of an existing one.  We found that this works better, because the user provides the alternate phrasing (via the matcher name) that expresses the negation that we can use for the `description` and `failure_message`.  So, for example, `RSpec::Matchers.define_negated_matcher :exclude, :include` defines `exclude` and we can simply substitute "exclude" for "include" in the description and failure message and it reads well and is very understandable.

**Comment by JonRowe** [comment]
I'm happy with `define_negated_matcher` FWIW

**Comment by postmodern** [comment]
I'm curious why the built-in matchers don't have negated forms by default?

**Comment by myronmarston** [comment]
> I'm curious why the built-in matchers don't have negated forms by default?

For one, because no one has ever asked for it before.  `define_negated_matcher` was new in RSpec 3.1.

I'm also concerned that many (perhaps most) of the matchers have multiple ways to phrase negation and the "best" way is subjective and non-obvious.  I don't want to add a bunch of negated forms and than have users suggest alternatives that are better and have to keep adding new APIs to RSpec for this.  I think a better way to go about it would be a gem that provides all these, that the community can contribute to until we have a consensus, and then we can consider rolling it into RSpec.

There's also the issue of the aliases we added that read well for composability -- when building composed matchers we offer non-phrase aliases for the build in matchers, and another use case for defining a negated matcher is to pass a negated matcher to another one -- e.g. `expect { }.to raise_error(a_string_excluding("boom"))` -- `a_string_excluding` would be a negation of `a_string_including` which is an alias of `include`.  If we ship negated forms for all the built-in matchers it suggests we should ship them for all the aliases as well....and now we're talking about serious API bloat.

All in all, it seems better to let users meet their own needs with the simple use of `define_negated_matcher`.

**Comment by myronmarston** [comment]
Closing as there's nothing clearly actionable here given our past choice to go with `define_negated_matcher` over a negation operator.
