### ISSUE TITLE
Allow .to_not all(...)

### ISSUE THREAD

**Issue by postmodern** [rspec/rspec-expectations#738]
This is basic boolean logic of [De Morgan's Law](http://en.wikipedia.org/wiki/De_Morgan%27s_laws) of applying a negation to a [Conjunctive Normal Form](http://en.wikipedia.org/wiki/Conjunctive_normal_form) to convert it into a [Disjunctive Normal Form](http://en.wikipedia.org/wiki/Disjunctive_normal_form).

**Comment by myronmarston** [comment]
Just to confirm, is this the kind of thing you'd like to be able to do?

``` ruby
expect([1, 2, 3, 5, 7, 9, 11]).not_to all be_odd
```

That would pass if we supported it (since `2` is not odd).  As it stands, you can already achieve this with `include`:

``` ruby
RSpec::Matchers.define_negated_matcher :a_value_that_is_not_odd, :be_odd
expect([1, 2, 3, 5, 7, 9, 11]).to include a_value_that_is_not_odd
```

IMO, this is better than the `not_to all` form because if we supported `not_to all`, I think some some users would use it when they intend to specify that _all_ numbers are not odd.

**Comment by myronmarston** [comment]
BTW -- given our commitment to SemVer and that it is far easier to add support for something than to take it away, we tend to err on the side of initially not supporting something that seems prone to misunderstanding, knowing we can easily add it in later, so that's part of what drove us to initially support `not_to all`.

Do you have some cases where `not_to all` works better than using `include(negated_matcher)`?

**Comment by myronmarston** [comment]
Closing for lack of a response.  Will gladly reopen if @postmodern wants to continue the conversation.
