### ISSUE TITLE
raise_error has identity issues with ArgumentError for kwargs

### ISSUE THREAD

**Issue by krainboltgreene** [rspec/rspec-expectations#875]
```
Failure/Error: expect { call }.to raise_error(ArgumentError.new("missing keywords: #{_body.parameters.map(&:last).join(', ')}"))
       expected #<ArgumentError: missing keywords: c, d>, got #<ArgumentError: missing keywords: c, d> with backtrace:
```

``` ruby
expect { call }.to raise_error(ArgumentError.new("missing keywords: #{_body.parameters.map(&:last).join(', ')}"))
```

**Comment by krainboltgreene** [comment]
Argh, nevermind, apparently I though I tried the the `raise_error(Class, Message)` but I had a typo. Trying that now works. I'm not sure what the difference here is tho.

**Comment by myronmarston** [comment]
Are you saying it failed with `raise_error` but worked with `raise_exception`?  That's odd and sounds like something we should fix -- they are just aliases and shouldn't behave different.

**Comment by mrageh** [comment]
Hi @krainboltgreene

I am trying to create a fix for this issue and just wanted to make sure I understood the problem correctly.

The first one below is the failing case and the one beneath it is the passing case right?

```
expect { raise ArgumentError, "missing keywords: c, d" }.to raise_error(ArgumentError.new("missing keywords: c, d")) #fails
```

```
expect { raise ArgumentError, "missing keywords: c, d" }.to raise_error(ArgumentError, "missing keywords: c, d") #passes
```

**Comment by krainboltgreene** [comment]
Yah, I believe so.

**Comment by mrageh** [comment]
Thank you, I'll try to solve this today

**Comment by mrageh** [comment]
@myronmarston I've looked into this issue and the reason why the first example fails and the second one passes is because the way `Exception#===`  works. In the first example `RaiseError's` `@expected_error` is `ArgumentError.new("missing keywords: c, d")` and the `@actual_error` is another instance of the same class. So when `FuzzyMatcher.values_match?`  does the fuzzy matching this [line](https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/fuzzy_matcher.rb#L18) is run and that returns `false` because `@actual_error` backtrace is different from `@expected_error` backtrace which is empty. 

However in the second example `@expected_error` is actually `ArgumentError` so when the fuzzy matching is done this [time](https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/fuzzy_matcher.rb#L18) it returns `true`. 

I think the above explanation is probably what's happening and there are several possible solutions to the problem above. In the `FuzzyMatcher.values_match?` maybe we can start comparing exceptions by the type and message, if those two things match it may be safe to assume that the correct error was raised?

**Comment by JonRowe** [comment]
TBH I'd expect this to fail, because you're not raising the specific instance...
```
expect { raise ArgumentError, "missing keywords: c, d" }.to raise_error(ArgumentError.new("missing keywords: c, d"))
```

Does this work though?:
```
error = ArgumentError.new("missing keywords: c, d")
expect { raise error }.to raise_error(error)
```

**Comment by krainboltgreene** [comment]
Realistically I only tried the failing one because I thought the regular thing wasn't worked. It was actually not working because I typo'd the message (`join(',')` instead of `join(', ')`). It might be worthwhile to just have a message print out.

**Comment by myronmarston** [comment]
> TBH I'd expect this to fail, because you're not raising the specific instance...

I expected it to work, because I knew exceptions have a reasonable definition of `==`.  However, I forgot that `backtrace` is part of that, and the backtraces are naturally different.

We could do something to try to normalize or exclude the backtraces from the match comparison but I think it's a bad idea.  If someone is passing us an exception instance (instead of just class and message) then we should only say it matches if it does in fact match.

So I don't think there's a bug here after all.

**Comment by JonRowe** [comment]
Neither do I

**Comment by krainboltgreene** [comment]
Turns out this also happens when you re-raise an exception.
