### ISSUE TITLE
Block matchers swallow nested expectations' failures

### ISSUE THREAD

**Issue by severinraez** [rspec/rspec-expectations#890]
Hi

As @trotzig and me found out in https://github.com/brigade/db-query-matchers/issues/11

    RSpec::Matchers.define :foo do
      match do |actual|
        actual.call
        true
      end
    
      def supports_block_expectations?
        true # or some logic
      end
    
      def failure_message
        'I failed'
      end
    end
    
    describe '#reraise' do
      context 'when some other expectation in the block fails' do
        subject {
          raise RSpec::Expectations::ExpectationNotMetError.new('other')
        }
    
        it 'reraises the error' do
          expect do
            expect { subject }.to foo
          end.to raise_error(RSpec::Expectations::ExpectationNotMetError, /other/)
        end
      end
    end

Fails with

    F
    
    Failures:
    
      1) #reraise when some other expectation in the block fails reraises the error
         Failure/Error:
           expect do
             expect { subject }.to foo
           end.to raise_error(RSpec::Expectations::ExpectationNotMetError, /other/)
    
           expected RSpec::Expectations::ExpectationNotMetError with message matching /other/, got #<RSpec::Expectations::Expecta
    tionNotMetError: I failed> with backtrace:
             # ./spec/db_query_matchers/make_database_queries_spec.rb:26:in `block (4 levels) in <top (required)>'
             # ./spec/db_query_matchers/make_database_queries_spec.rb:25:in `block (3 levels) in <top (required)>'
         # ./spec/db_query_matchers/make_database_queries_spec.rb:25:in `block (3 levels) in <top (required)>'
    
    Finished in 0.01832 seconds (files took 1.15 seconds to load)
    1 example, 1 failure

This increases the difficulty of finding the cause of a failing spec that uses nested expectations as the spec will provide an unusable hint in the failure message.

Is this by design or would you consider it a bug? Any suggestions on how one could contribute a fix?

Cheers,
Severin

**Comment by myronmarston** [comment]
This is (kind of) working as designed.  When you use the matcher DSL, we support you defining your match logic by delegating to another expectation:

``` ruby
RSpec::Matchers.define :be_positive do
  match do |value|
    expect(value).to be > 0
  end
end
```

(In this case, the `match` logic could be simplified to `value > 0` but you can imagine cases where it's easier to express the logic using an expectation than a boolean expression).

This is implemented by having our [match](https://github.com/rspec/rspec-expectations/blob/v3.4.0/lib/rspec/matchers/dsl.rb#L59-L70) method rescue `RSpec::Expectations::ExpectationNotMetError`.

In your case, you aren't using an expectation as part of your `match` logic, but since the block is called in it, the `rescue` still applies and leads to this confusing behavior.  It'd be nice to find a way to apply the `rescue` only to expectations defined w/in the `match` block itself, and not to expectations that happen in blocks your `match` logic calls...but I can't think of a way to do that.

Note that this only applies if you use the `match` method on the matcher DSL, so on your end you could work around this by using `def matches?` (or `define_method :matches?`) instead of `match`:

``` ruby
RSpec::Matchers.define :make_database_queries do |options = {}|
  define_method :matches? do |block|
    # match logic goes here
  end

  # the rest of your DSL usage can stay the same
end
```

Here you need to use `define_method :matches?` to have access to `options` as a normal `def matches?` would not.

Does that help?

**Comment by severinraez** [comment]
Thanks for the help, @myronmarston ! Would've taken me a lot of time to track this down.
That did indeed fix the problems, i submitted a PR over at db-query-matchers.

Closing because fixing this in rspec-expectations has gotten it's own PR by now :)
