### ISSUE TITLE
Flaky behavior on Ubuntu

### ISSUE THREAD

**Issue by fmorales** [rspec/rspec-expectations#901]
I have some code that run's matchers in minitest::spec and in minitest::test. I am trying to use both rspec and minitest expectations. Everything works great on OSX, but when we try it on any of our linux box's, rspec matchers do not work. 

Here is the code, and the error from the linux machine:
https://gist.github.com/fmorales/6efbdd6094fa95b7f0f3

**Comment by myronmarston** [comment]
Are you running different versions of minitest on the two machines?  

I believe the problem is that minitest added an `expect` method in minitest 5.6.0:

https://github.com/seattlerb/minitest/commit/9e78cc974f3ef0d9716f1cca2675753cf5f648d0

As a result when `RSpec::Matchers` is included in minitest < 5.6, `expect(x)` returns an RSpec object that has a `to` method.  When `RSpec::Matchers` is included in minitest >= 5.6, `expect(x)` returns a minitest object that does _not_ have a `to` method because Minitest's `expect` is taking precedence.

This problem is discussed in detail in rspec/rspec-mocks#931, but we haven't yet fixed it.  If you pin to minitest < 5.6 it should work for now.

**Comment by fmorales** [comment]
Thank you so much. That sorted it!
