### ISSUE TITLE
Minitest breaks rspec-expectations minitest_integration

### ISSUE THREAD

**Issue by tscholz** [rspec/rspec-expectations#902]
Hi there,

first, thank you for this great gem!

While upgrading our application from Rails 3 to Rails 4 we run into the same problem as described [here](https://github.com/codeodor/minitest-rspec_mocks/issues/4) with rspec-expectations.

I'm not sure if the workaround I've found [here](https://github.com/codeodor/minitest-rspec_mocks/commit/e67ac54402843878671e11ea407df86730ea8c0c) is the way to go and if similar code should be added to `lib/rspec/expectations/minitest_integration.rb`.

Please let me know what you think about.

**Comment by myronmarston** [comment]
For a work around in a single project or in an extension gem, I think that approach is fine.  For something in RSpec proper, I think it's suboptimal.  Ideally, we would solve the conflict w/o removing Minitest's method, so that the APIs from both libraries can be used as the user sees fit.  I think we can make it work by adding `to` and `not_to`/`to_not` to `Minitest::Expectation` (e.g. by moving those methods to a module that can be mixed into `RSpec::Expectations::ExpectationTarget` and `Minitest::Expectation`).  We'd also have to check about the block form of `expect` (e.g. `expect { ... }`) to make sure that will still work.

**Comment by myronmarston** [comment]
@tscholz -- there's a fix in #904 if you want to give that a try.
