### ISSUE TITLE
One-line syntax specs don't show proper documentation when dry-running

### ISSUE THREAD

**Issue by obfuscoder** [rspec/rspec-expectations#931]
Using rspec -fd --dry-run on  a project with one-liner specs like

```ruby
it { is_expected.to eq true }
```

only show up as

```
   example at ./spec/path/to/spec.rb:24
```

When actually running the specs I get the correct output.

I know that dry-running does not execute the code, but only collects the specs and their description. I would love to have the specs also evaluate the expectation strings when dry-running one-liner. Maybe another run-mode might be appropriate to not slow down dry-running, but to get the expactation evaluation. After all, I would like to use this to get a readable and presentable documentation of all my specs including the one-liner without actually running the tests.

**Comment by JonRowe** [comment]
Thanks for the feedback, but as you point out  `--dry-run` doesn't execute the spec, thus it isn't possible to gather a description for the one line syntax. 

This is one of the many reasons we advocate writing your spec doc strings yourself instead of relying on the auto-generated ones, we simply are often unable to guess your meaning, writing them yourself is the best way to get readable and presentable documentation :)

**Comment by dcarral** [comment]
@JonRowe Just arrived to this issue after having been bitten by this issue. 

In my opinion it's extremely interesting to take into account the comment made 5 years ago by @dchelimsky regarding this topic @ https://github.com/rspec/rspec-core/issues/354:

> Self-describing matchers/one-liners, which must be executed in order to generate their documentation, render --dry-run unusable for most users, so it's not included in rspec-2.

I'd like to ask you folks (@samphippen @myronmarston also since they reviewed https://github.com/rspec/rspec-core/pull/1028): what do you think about adding a note regarding this to the `--dry-run` docs @ _rspec-core_?

**Comment by myronmarston** [comment]
> I'd like to ask you folks (@samphippen @myronmarston also since they reviewed https://github.com/rspec/rspec-core/pull/1028): what do you think about adding a note regarding this to the `--dry-run` docs @ _rspec-core_?

I'm in favor.  Want to open a PR to improve the docs?
