### ISSUE TITLE
contain_exactly and match_array fail for objects that implement equal? but are not sortable

### ISSUE THREAD

**Issue by malakai97** [rspec/rspec-expectations#964]
I've created a minimal code sample [here](https://github.com/malakai97/rspec-bug) that illustrates the problem.  The repo includes a Gemfile that should provide sufficient version information.

```
~/code/rspec-bug$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by myronmarston** [comment]
`equal?` should only return `true` when comparing two references to the exact same object.  To quote the [ruby docs](http://ruby-doc.org/core-2.4.0/Object.html#method-i-eql-3F):

> Unlike ==, the equal? method should never be overridden by subclasses as it is used to determine object identity (that is, a.equal?(b) if and only if a is the same object as b):

In your example, you've overriden `Object#equal?` (which Ruby explicitly tells you not to do) so that it returns `true` when given two different objects that happen to have the same value for the `foo` attribute.  This violates the semantics of what the `equal?` method is intended for and how RSpec expects it to behave.

We're not able to support objects that violate the semantics of core ruby protocols like `equal?` so we're not going to fix this.
