### ISSUE TITLE
Pass a block to matcher

### ISSUE THREAD

**Issue by wkrsz** [rspec/rspec-expectations#98]
Currently I'm doing something like:

```
expect { ... }.to send_an_email_to("example@example.com").
    which(lambda{|email| email.subject =~ /expected/ })
```

Whereas I would like to do the following:

```
expect { ... }.to send_an_email_to("example@example.com").
    which{|email| email.subject =~ /expected/ }
```

In other words I'd like to get rid of the lambda.

Following hack seems to do the trick:

```
RSpec::Matchers::Matcher.class_eval do
  #override chain to pass blocks too
  def chain(method, &block)
    define_method method do |*args, &chain_block|
      block.call(*args, &chain_block)
      self
    end
  end
end
```

Whatcha think?

I haven't used Rspec2 since the fall of The Berlin Wall and I'm just getting my feet wet so it's totally possible I'm doing it very backwards (-:

**Comment by nwallace** [comment]
Does this still work in RSpec 3?  I'm trying to do the same thing (in this gem: https://github.com/nwallace/active_record_block_matchers).  I want to be able to say that a block inserts a record into the database, then chain a block that takes the newly-inserted record as an argument (so I can make assertions on the record), like this:

```ruby
expect {
  User.create!(email: "expected@example.com", password: "pass123")
}.to create_a(User)
  .which do |user|
    expect(user.encrypted_password).to be_present
  end
```

Here's my matcher definition at the moment:

```ruby
RSpec::Matchers.define :create_a_new do |klass|
  supports_block_expectations

  def which(&block)
    @which_block = block
    self
  end

  match do |block|
    time_before = Time.current
    block.call
    @created_records = klass.where("created_at > ?", time_before)
    if @created_records.count == 1
      @which_block.call(@created_records.first) if @which_block
      true
    else
      false
    end
  end
end
```

But the `which` method doesn't receive the block as an argument (the method is called, but `block` is nil), so when `match` is run, it doesn't call the `@which_block`.

I noticed that if I declare the block in my example with curly braces instead of a `do...end`, I get a different error that shows no backtrace (just errors out on the initial `expect` call).

Is this possible to do with RSpec 3?  Furthermore, I've had a lot of trouble finding documentation on the interface for custom matchers *without* the DSL macros.  Is there documentation out there on that?

Thanks!

**Comment by myronmarston** [comment]
So, several things here...

* The problem you're seeing is the precedent of your `do...end` block.  This expectation:

``` ruby
expect {
  User.new("expected@example.com", "pass123")
}.to create_a_new(User).which do |user|
  expect(user.encrypted_password).to be_present
end
```

...is equivalent to:

``` ruby
expect {
  User.new("expected@example.com", "pass123")
}.to(create_a_new(User).which) do |user|
  expect(user.encrypted_password).to be_present
end
```

IOW, the block binds to `to`, not to `which`.  To make the block bind to `which`, you can use curly braces:

``` ruby
expect {
  User.new("expected@example.com", "pass123")
}.to create_a_new(User).which { |user|
  expect(user.encrypted_password).to be_present
}
```

Putting this together in a full example (that substitutes some things to be usable in isolation outside your app), I've got this, which works as I expect:

``` ruby
User = Struct.new(:email, :password, :encrypted_password) do
  def initialize(*args)
    super
    self.class.created_records << self
  end

  def self.created_records
    @created_records ||= []
  end
end

RSpec::Matchers.define :create_a_new do |klass|
  supports_block_expectations

  def which(&block)
    @which_block = block
    self
  end

  match do |block|
    block.call
    @created_records = User.created_records
    if @created_records.count == 1
      @which_block.call(@created_records.first) if @which_block
      true
    else
      false
    end
  end
end

RSpec.describe "Using the matcher" do
  it 'works as expected' do
    expect {
      User.new("expected@example.com", "pass123")
    }.to create_a_new(User).which { |user|
      expect(user.encrypted_password).to be_present
    }
  end
end
```

> I noticed that if I declare the block in my example with curly braces instead of a do...end, I get a different error that shows no backtrace (just errors out on the initial expect call).

What is the error you see?  The error I see (when `encrypted_password` is not present) is exactly what I expect:

```
expected #<Proc:0x007fb7858de8e0@/Users/myron/code/rspec-dev/repos/rspec-expectations/spec/foo_spec.rb:34> to create a new User
```

OTOH, when I put a passing expectation in the `which` block, it passes, as expected.

One thing you might not realize is that within `match` in the matcher DSL, we allow you to use expectations, and rescue `RSpec::Expectations::ExpectationNotMetError` and make it return `false` to indicate it did not match.  Thus, the failure message you get is simply the failure message for your `create_a_new` matcher, not for the `be_present` matcher.

BTW, the point above about `chain` not accepting blocks is no longer accurate.  It does in RSpec 3.  See this spec for an example:

https://github.com/rspec/rspec-expectations/blob/f69cc918be1bdaccdb8f85877178c62d89439bdc/spec/rspec/matchers/dsl_spec.rb#L1037-L1045

> I've had a lot of trouble finding documentation on the interface for custom matchers without the DSL macros. Is there documentation out there on that?

We have a document the matcher protocol here:

http://rspec.info/documentation/3.2/rspec-expectations/RSpec/Matchers/MatcherProtocol.html

Any object that implements that protocol can be used as a matcher.

**Comment by myronmarston** [comment]
BTW, in the future, please open a new issue instead of commenting on an old one.  If I'm not able to immediately respond I'm likely to forget for a question like yours since it's not on an open issue and thus doesn't show up on our issues list.

**Comment by nwallace** [comment]
<3 Amazing. Thank you Myron!  I understand now.  The error I was seeing when using curly braces was due to the `which_block` raising `RSpec::Expectations::ExpectationNotMetError`.  I had a typo in my block that caused it to fail when I expected it to succeed, thus leading to the confusion.

Any, thank you for the detailed response. I'll raise new issues in the future, if necessary :)
