### ISSUE TITLE
not_to have_attributes fails when an attribute has a string value in actual and nil value in expected

### ISSUE THREAD

**Issue by brunofacca** [rspec/rspec-expectations#996]
Given an ActiveRecord model instance called `person`:
`#<Person id: 1, first_name: "John", last_name: "Doe", age: 1, created_at: "2017-06-22 19:12:29", updated_at: "2017-06-22 19:12:29">` 

and the following params hash:
`invalid_attributes = {:first_name => "Larry", :last_name => nil, :age => 1}`

the following assertion:
`expect(person).not_to have_attributes(invalid_attributes)` 

fails with the following error:

     Failure/Error: expect(person).not_to have_attributes(invalid_attributes)
       expected #<Person id: 1, first_name: "John", last_name: "Doe", age: 1, created_at: "2017-06-22 19:12:29", updated_at: "2017-06-22 19:12:29"> not to have attributes {:first_name => "Larry", :last_name => nil, :age => 1}

I believe the assertion should pass, given that the `person` and `invalid_attributes` have different values for `last_name`.

**Comment by myronmarston** [comment]
The expectation is failing because `invalid_attributes` includes `age: 1` and the `age` attribute in fact has the value of 1.  `not_to have_attributes(hash_of_attributes)` is designed to only pass if _none_ of `hash_of_attributes` match.

Consider what would happen if we implemented `have_attributes` like you're asking: if you did `not_to have_attributes(hash_of_100_attributes)` then it would mean it would pass as long as any one of the 100 attributes had a different value.  The other 99 attributes would be ignored and not even considered.  That makes for a weak expectation that gets weaker with each additional attribute added to the expectation.

Can you explain why you want `have_attributes` to work that way?

**Comment by brunofacca** [comment]
@myronmarston Thanks for taking the time to explain that. 

The [`have_attributes` documentation](https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/have-attributes-matcher) says: 
> fails if any of the attributes don't match

I inferred that the opposite behavior (triggered by `not_to`) would be to "pass if any of the attributes don't match". In hindsight, I realize that sentence can also be inverted as "fails is any of the attributes matches". Maybe we could clarify that in the docs. I can submit a PR to [the docs](https://github.com/rspec/rspec-expectations/blob/master/features/built_in_matchers/have_attributes.feature) if you are interested.

Regarding why I want `have_attributes` to work that way, I expected to use it to ensure a resource is not updated when provided invalid attributes, as in the following spec:

    RSpec.describe PeopleController, type: :controller do
      describe 'PATCH #update', :focus do
        let (:person) { FactoryGirl.create(:person) }

        context "with invalid attributes" do
          let (:invalid_attributes) do
            FactoryGirl.attributes_for(:person, first_name: 'John', last_name: nil)
          end

          it "does not update the requested person" do
            patch :update, id: person, person: invalid_attributes
            person.reload
            expect(person).not_to have_attributes(invalid_attributes)
          end
        end
      end
    end

After discovering that `have_attributes` did not work as I initially expected, I have replaced the above example with the following:

    it "does not update the requested person" do
      expect {
        patch :update, id: person, person: invalid_attributes
        person.reload
      }.not_to change {person}
    end

**Comment by myronmarston** [comment]
One thing to keep in mind is that for many of the matchers, the `not_to matcher` logic is _not_ exactly equivalent to the inverse of `to matcher`.  So this behavior that surprised you is completely normal.

For example, `expect("a").to be_even` and `expect("a").not_to be_even` both fail, because `"a"` does not have a an `even?` predicate.  If you're using `expect(x).not_to be_blah` we assume you're expecting `x` to have a `blah?` method, and that you want it to fail if you typo'd it or something.

Likewise, several of the matchers take a variable number of arguments, such as `respond_to(:foo, :bar)`, `include(x, y)`, `have_attributes(x: a, y: b)`, and `cover(a, b)`.  For all of these, the positive match logic requires that _all_ of the provided items match, and likewise the negative match logic requires that _none_ of the provided items match (rather than requiring that at least one does not match).

All that's to say: we definitely welcome improvements to our docs, but this isn't a unique thing about the `have_attributes` matcher, so there might be a more holistic way to go about improving the docs as a whole (or maybe the answer is to improve the docs of all of these matchers...).  So yes, if you've got ideas to improve the docs, please submit a PR :).

Anyhow, regarding what you changed the expectation into: you've definitely got the right idea there, but I suspect that that spec won't fail even if the `person` attributes are updated.  That's because ActiveRecord defines `==` so that it checks the id....so `Person.find(1) == Person.find(1)` will always be `true` even if the attributes of that record changed between the two `find` calls.  Actually, in your case, it's the exact same object instance, so you're also contending with the fact that it's the same object instance.  To fix it, try using `change { person.attributes }`.  That'll return a hash of attributes, and ensure that it's only considering the attribute values when determining if it changed, rather than considering the identity of the `person` record.

**Comment by brunofacca** [comment]
@myronmarston: 

Thank you very much for taking the time to explain that. I'm sorry for spending your time with something that's not a bug. 

I'll try to come up with a way to update the docs without repeating the explanation regarding the negative matching behavior in all the matchers you have mentioned.

Regarding my spec, you are right, `change { person }` always passes because it's the same object . However, something unexpected happened when using `change { person.attributes }`:

    Failure/Error:
       expect {
         patch :update, id: person, person: invalid_attributes
         person.reload
       }.not_to change {person.attributes}

    expected result not to have changed, but did change from {"id"=>1, "first_name"=>"MyString", "last_name"=>"MyString", "age"=>1, "created_at"=>2017-06-23 16:55:39.544720797 +0000, "updated_at"=>2017-06-23 16:55:39.544720797 +0000} to {"id"=>1, "first_name"=>"MyString", "last_name"=>"MyString", "age"=>1, "created_at"=>2017-06-23 16:55:39.544720000 +0000, "updated_at"=>2017-06-23 16:55:39.544720000 +0000}

Note that the difference lies in the `created_at` and `updated_at` attributes, as their last 4 decimal digits were somehow zeroed.

**Comment by myronmarston** [comment]
The failure is because the timestamps in memory in ruby (which are set before the record is saved in the DB) are very precise (to the point of having 9 decimal places of sub-second precision!), but your database rounds the timestamps off to 5 decimal places--which means that when the record is reloaded, it drops some of the decimal places.  So the before/after values you are comparing have different levels of precision.

There are two basic solutions:

* Force the timestamps to nice, round values that won't be further rounded by the database (e.g. by explicitly setting `created_at` and `updated_at` when creating the record)
* Change the spec so the block passed to `change` always loads the data from from the DB (even for the first time).

Here's an example of what you could do for the 2nd option:

``` ruby
it "does not update the requested person" do
  expect {
    patch :update, id: person, person: invalid_attributes
  }.not_to change { Person.find(person.id).attributes }
end
```

This is probably the option I'd go for.  It better expresses the idea "does not change the attributes stored in the database"--which is what you care about, I think.

**Comment by brunofacca** [comment]
@myronmarston: Your code for the 2nd option works perfectly. Again, thank you for explaining the issue so thoroughly. This discussion taught me a lot about some of the quirks involved in testing a Rails app with RSpec.

**Comment by myronmarston** [comment]
Cool.  I'm going to close this, but we certainly still welcome a PR to improve our docs.

**Comment by brunofacca** [comment]
@myronmarston: One last question: Is `not_to change { Person.find(person.id).attributes }` the same as `not_to change { person.reload.attributes }`? The example seems to work either way and the latter does not rely on the ID. Thank you.

**Comment by myronmarston** [comment]
Yes, I'd expect them to be the same.
